### ISSUE TITLE
Upstreaming your decoder

### ISSUE THREAD

**Issue by abraxa** [pakesson/sigrok-sdq-decoder#1]
Hi, would you consider upstreaming your PD so it can be included in the collection of official PDs?

https://sigrok.org/wiki/Protocol_decoder_HOWTO#Submitting_your_decoder

**Comment by pakesson** [comment]
Hey! Absolutely, I'll see if I can find the time to clean it up and submit it during the summer.

**Comment by pakesson** [comment]
I created a PR for the protocol decoder: https://github.com/sigrokproject/libsigrokdecode/pull/49

I also added some example data here in this repo.

**Comment by gsigh** [comment]
Your decoder went mainline. Thank you!
